on: push
name: on push
jobs:
  gitHubActionForPylint:
    name: Python linting
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: GitHub Action for pylint
      uses: zerodaysec/github-action-for-python@main
      with:
        args: pipenv run pip list && pylint --help
