name: CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  smokeTest:
    name: Python linting
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: GitHub Action for pylint
      uses: zerodaysec/github-action-for-python@main
      with:
        args: pipenv run pip list && pylint --help
